### ISSUE TITLE
Help Intent not working!

### ISSUE THREAD

**Issue by sspike2** [alexa/skill-sample-nodejs-berry-bash#11]
Whenever we start the skill and call for help it goes into unknown intent instead of help intent

**Comment by franklin-lobb** [comment]
Can you provide a little more information as to what is happening? There is no unknown intent (or even fallback intent), so is the HelpIntent being triggered but the message associated with `handleUnknown` being returned?  Is there an 'Error handled:' message with error details in the logs?

**Comment by sspike2** [comment]
![image](https://user-images.githubusercontent.com/34025910/49716156-dd11b380-fc78-11e8-865b-2f71ddef03a3.png)

**Comment by franklin-lobb** [comment]
Still looking into it, however the HelpIntent is being triggered, however the issue is that there's an error 'cannot read property of undefined - requestenvelope' which is thrown from somewhere within the help handler.  If you find the source of that, the help should work correctly.  I hope to have time to look at that this morning.

**Comment by franklin-lobb** [comment]
Found the issue -- looks like a few things were missed when the skill was updated to the new SDK.  Replace
```newSessionHandler.call(this);``` with ```newSessionHandler(handlerInput);```
in the HelpIntentHandler (and NextIntentHandler).
